applicationSettings: {}
pipeline:
  - id: pipelines/fipfo
    config:
      input:
        # The crypto resource wraps the generator resource.
        - id: utilities/crypto/v1
          config:
            mode: encrypt
            password: iddX0DQKGMl7LszqdDKUL6aFVvMGAtwd
          nodes:
            - id: utilities/generators/v1
              config:
                interval: 1s
                numberEvents: 1
                numberCollections: 1
      output:
        # Decrypt the events before writing the output to console.
        - id: utilities/crypto/v1
          config:
            mode: decrypt
            password: iddX0DQKGMl7LszqdDKUL6aFVvMGAtwd
          nodes:
            - id: utilities/console/v1
