applicationSettings: {}
pipeline:
  - id: pipelines/fipfo
    config:
      input:
        # Wrap a resource with a performance measuring resource.
        - id: utilities/performance/v1
          config:
            sampleWindow: 10s
          nodes:
            - id: utilities/generators/v1
              config:
                interval: 1s
                numberEvents: 1000
                numberCollections: 1000
      output:
        - id: utilities/console/v1
