name: release-manual-major

on: [workflow_dispatch]

jobs:
  push_to_registry:
    name: release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.1.0

      - id: release
        uses: rymndhng/release-on-push-action@v0.16.0
        with:
          # If the PR has the label release:major, release:minor, or release:patch, this will override bump_version_scheme
          bump_version_scheme: major

